In [1]:
import pandas as pd
import geopandas as gpd
from shapely.geometry import shape
import json

In [2]:
df = gpd.read_file("forest_fires_nutsall_mapbox_4326.geojson")

In [15]:
winter_season = ['January', 'February', 'March', 'November', 'December']
fire_season = ['April', 'May', 'June', 'July', 'August', 'September', 'October']

df_fire_season = df[df['month'].isin(fire_season)]
df_winter_season = df[df['month'].isin(winter_season)]

In [16]:
natura = gpd.read_file(
    r"C:\Users\kwnst\Downloads\forest_fires\SHP\SHP\Natura2000_end2024_epsg3035.shp"
)
df_3035 = df_fire_season.to_crs(natura.crs)

In [17]:
overlaps = gpd.overlay(
    df_3035,
    natura,
    how="intersection",
    keep_geom_type=True
)
overlaps

,id,country,province,commune,firedate,area_ha,broadleaved_forest_pct,coniferous_forest_pct,mixed_forest_pct,sclerophyllous_vegetation_pct,...,nuts_country,total_geometry_area_ha,geometry_area_ha_normalized,SITECODE,SITENAME,RELEASE_DA,MS,SITETYPE,INSPIRE_ID,geometry
0,285364,RO,Tulcea,Jurilovca,2025-10-30 23:07:00+00:00,59,0.000000,0.0,0.000000,0.0,...,RO,59.245868,59.0,ROSCI0065,Delta Dunării,2024-09-11,RO,B,NaN,"POLYGON ((5810594.203 2594520.72, 5810595.2 2594508.753, 5810589.217 2594504.764, 5810555.311 2594486.814, 5810493.484 2594454.903, 5810412.709 2594401.054, 5810312.987 2594325.265, 5810178.363 2594236.513, 5810008.836 2594134.796, 5809918.089 2594081.944, 5809906.122 2594077.955, 5809866.234 2594060.005, 5809798.423 2594028.094, 5809744.573 2593997.18, 5809704.684 2593967.264, 5809640.862 2593945.325, 5809553.107 2593931.364, 5809464.355 2593912.417, 5809374.605 2593888.484, 5809303.803 2593863.553, 5809251.947 2593837.625, 5809183.139 2593807.709, 5809097.379 2593773.803, 5809003.64 2593738.901, 5808901.924 2593703.001, 5808822.146 2593678.071, 5808764.308 2593664.109, 5808717.439 2593648.154, 5808681.539 2593630.204, 5808650.625 2593601.285, 5808624.697 2593561.396, 5808599.767 2593525.496, 5808575.834 2593493.585, 5808553.895 2593461.674, 5808533.951 2593429.763, 5808519.989 2593400.844, 5808512.012 2593374.916, 5808500.045 2593357.964, 5808484.09 2593349.986, 5808463.148 2593354.972, 5808437.22 2593372.922, 5808405.309 2593411.813, 5808367.415 2593471.646, 5808340.49 2593529.485, 5808324.535 2593585.329, 5808305.588 2593659.123, 5808283.649 2593750.867, 5808278.663 2593811.698, 5808290.629 2593841.614, 5808298.607 2593867.542, 5808302.596 2593889.481, 5808302.596 2593909.425, 5808298.607 2593927.375, 5808299.604 2593943.331, 5808305.588 2593957.292, 5808338.496 2593947.319, 5808398.329 2593913.414, 5808440.212 2593894.467, 5808464.145 2593890.478, 5808503.037 2593894.467, 5808556.887 2593906.433, 5808629.683 2593913.414, 5808721.427 2593915.408, 5808775.277 2593914.411, 5808791.233 2593910.422, 5808813.172 2593894.467, 5808841.094 2593866.545, 5808863.032 2593862.556, 5808878.988 2593882.5, 5808894.943 2593901.447, 5808910.899 2593919.397, 5808923.863 2593928.372, 5808933.835 2593928.372, 5808974.721 2593932.361, 5809046.521 2593940.339, 5809116.326 2593961.28, 5809184.137 2593995.186, 5809242.972 2594024.105, 5809292.833 2594048.038, 5809331.725 2594074.963, 5809359.647 2594104.88, 5809401.53 2594127.816, 5809457.374 2594143.771, 5809498.26 2594149.755, 5809524.188 2594145.766, 5809560.088 2594154.741, 5809605.96 2594176.68, 5809646.846 2594212.579, 5809682.746 2594262.44, 5809732.606 2594294.351, 5809796.428 2594308.312, 5809851.275 2594319.282, 5809897.147 2594327.259, 5809946.011 2594346.207, 5809997.866 2594376.123, 5810050.719 2594420.998, 5810104.569 2594480.831, 5810139.471 2594513.739, 5810155.427 2594519.722, 5810180.357 2594519.722, 5810214.263 2594513.739, 5810261.132 2594508.753, 5810320.965 2594504.764, 5810355.868 2594504.764, 5810365.84 2594508.753, 5810370.826 2594522.714, 5810370.826 2594546.647, 5810380.798 2594573.572, 5810400.742 2594603.489, 5810429.662 2594614.458, 5810467.556 2594606.48, 5810510.436 2594589.528, 5810558.303 2594563.6, 5810586.225 2594540.664, 5810594.203 2594520.72))"
1,285364,RO,Tulcea,Jurilovca,2025-10-30 23:07:00+00:00,59,0.000000,0.0,0.000000,0.0,...,RO,59.245868,59.0,ROSPA0031,Delta Dunării și Complexul Razim - Sinoie,2024-09-11,RO,A,NaN,"POLYGON ((5810594.203 2594520.72, 5810595.2 2594508.753, 5810589.217 2594504.764, 5810555.311 2594486.814, 5810493.484 2594454.903, 5810412.709 2594401.054, 5810312.987 2594325.265, 5810178.363 2594236.513, 5810008.836 2594134.796, 5809918.089 2594081.944, 5809906.122 2594077.955, 5809866.234 2594060.005, 5809798.423 2594028.094, 5809744.573 2593997.18, 5809704.684 2593967.264, 5809640.862 2593945.325, 5809553.107 2593931.364, 5809464.355 2593912.417, 5809374.605 2593888.484, 5809303.803 2593863.553, 5809251.947 2593837.625, 5809183.139 2593807.709, 5809097.379 2593773.803, 5809003.64 2593738.901, 5808901.924 2593703.001, 5808822.146 2593678.071, 5808764.308 2593664.109, 5808717.439 2593648.154, 5808681.539 2593630.204, 5808650.625 2593601.285, 5808624.697 2593561.396, 5808599.767 2593525.496, 5808575.834 2593493.585, 5808553.895 2593461.674, 5808533.951 2593429.763, 5808519.989 2593400.844, 5808512.012 2593374.916, 5808500.045 2593357.964, 5808484.09 2593349.986, 5808463.148 2593354.972, 5808437.22 2593372.922, 5808405.309 2593411.813, 5808367.415 2593471.646, 5808340.49 2593529.485, 5808324.535 2593585.329, 5808305.588 2593659.123, 5808283.649 2593750.867, 5808278.663 2593811.698, 5808290.629 2593841.614, 5808298.607 2593867.542, 5808302.596 2593889.481, 5808302.596 2593909.425, 5808298.607 2593927.375, 5808299.604 2593943.331, 5808305.588 2593957.292, 5808338.496 2593947.319, 5808398.329 2593913.414, 5808440.212 2593894.467, 5808464.145 2593890.478, 5808503.037 2593894.467, 5808556.887 2593906.433, 5808629.683 2593913.414, 5808721.427 2593915.408, 5808775.277 2593914.411, 5808791.233 2593910.422, 5808813.172 2593894.467, 5808841.094 2593866.545, 5808863.032 2593862.556, 5808878.988 2593882.5, 5808894.943 2593901.447, 5808910.899 2593919.397, 5808923.863 2593928.372, 5808933.835 2593928.372, 5808974.721 2593932.361, 5809046.521 2593940.339, 5809116.326 2593961.28, 5809184.137 2593995.186, 5809242.972 2594024.105, 5809292.833 2594048.038, 5809331.725 2594074.963, 5809359.647 2594104.88, 5809401.53 2594127.816, 5809457.374 2594143.771, 5809498.26 2594149.755, 5809524.188 2594145.766, 5809560.088 2594154.741, 5809605.96 2594176.68, 5809646.846 2594212.579, 5809682.746 2594262.44, 5809732.606 2594294.351, 5809796.428 2594308.312, 5809851.275 2594319.282, 5809897.147 2594327.259, 5809946.011 2594346.207, 5809997.866 2594376.123, 5810050.719 2594420.998, 5810104.569 2594480.831, 5810139.471 2594513.739, 5810155.427 2594519.722, 5810180.357 2594519.722, 5810214.263 2594513.739, 5810261.132 2594508.753, 5810320.965 2594504.764, 5810355.868 2594504.764, 5810365.84 2594508.753, 5810370.826 2594522.714, 5810370.826 2594546.647, 5810380.798 2594573.572, 5810400.742 2594603.489, 5810429.662 2594614.458, 5810467.556 2594606.48, 5810510.436 2594589.528, 5810558.303 2594563.6, 5810586.225 2594540.664, 5810594.203 2594520.72))"
2,285361,ES,Alicante/Alacant,Elche / Elx,2025-10-30 10:51:00+00:00,7,0.000000,0.0,0.000000,0.0,...,ES,6.907481,7.0,ES0000058,el Fondo d'Elx-Crevillent,2024-12-11,ES,B,NaN,"POLYGON ((3375441.654 1746033.039, 3375437.256 1746049.363, 3375435.087 1746071.051, 3375435.087 1746090.571, 3375437.256 1746107.921, 3375440.871 1746120.573, 3375445.931 1746128.526, 3375454.245 1746130.333, 3375465.813 1746125.995, 3375475.211 1746115.874, 3375482.44 1746099.969, 3375491.477 1746079.004, 3375502.321 1746052.977, 3375510.629 1746031.691, 3375516.401 1746015.145, 3375519.655 1746007.554, 3375520.389 1746008.918, 3375522.564 1746006.709, 3375526.179 1746000.925, 3375533.408 1745985.743, 3375544.252 1745961.163, 3375557.627 1745924.654, 3375573.532 1745876.217, 3375586.545 1745844.769, 3375596.666 1745830.31, 3375604.98 1745811.513, 3375611.486 1745788.379, 3375612.932 1745770.666, 3375609.318 1745758.376, 3375602.088 1745749.339, 3375591.244 1745743.556, 3375582.93 1745733.073, 3375577.146 1745717.891, 3375564.856 1745701.625, 3375546.06 1745684.274, 3375518.588 1745670.538, 3375482.44 1745660.417, 3375447.739 1745644.512, 3375414.483 1745622.824, 3375378.336 1745602.943, 3375339.297 1745584.869, 3375303.872 1745566.434, 3375272.063 1745547.637, 3375245.675 1745533.901, 3375224.709 1745525.226, 3375208.443 1745519.442, 3375196.876 1745516.55, 3375179.887 1745501.73, 3375157.475 1745474.981, 3375135.425 1745455.461, 3375113.737 1745443.171, 3375095.663 1745437.026, 3375081.204 1745437.026, 3375069.637 1745441.002, 3375060.962 1745448.955, 3375059.154 1745459.799, 3375064.215 1745473.535, 3375084.819 1745487.994, 3375120.966 1745503.176, 3375148.8 1745519.442, 3375168.32 1745536.793, 3375183.501 1745550.529, 3375194.346 1745560.65, 3375205.913 1745569.687, 3375218.203 1745577.639, 3375228.324 1745588.845, 3375236.277 1745603.304, 3375249.651 1745613.064, 3375268.448 1745618.124, 3375282.907 1745632.945, 3375293.028 1745657.525, 3375304.957 1745670.538, 3375318.693 1745671.984, 3375332.067 1745667.285, 3375345.08 1745656.441, 3375357.37 1745650.657, 3375368.938 1745649.934, 3375377.974 1745653.187, 3375384.481 1745660.417, 3375403.639 1745682.105, 3375435.449 1745718.253, 3375454.607 1745738.495, 3375461.113 1745742.833, 3375474.126 1745754.039, 3375493.646 1745772.112, 3375494.007 1745797.777, 3375475.211 1745831.033, 3375464.367 1745858.143, 3375461.475 1745879.109, 3375459.306 1745903.327, 3375457.86 1745930.799, 3375455.751 1745962.551, 3375452.98 1745998.584, 3375448.28 1746022.079, 3375441.654 1746033.039))"
3,285361,ES,Alicante/Alacant,Elche / Elx,2025-10-30 10:51:00+00:00,7,0.000000,0.0,0.000000,0.0,...,ES,6.907481,7.0,ES0000484,el Fondo d'Elx-Crevillent (ZEPA),2024-12-11,ES,A,NaN,"POLYGON ((3375441.654 1746033.039, 3375437.256 1746049.363, 3375435.087 1746071.051, 3375435.087 1746090.571, 3375437.256 1746107.921, 3375440.871 1746120.573, 3375445.931 1746128.526, 3375454.245 1746130.333, 3375465.813 1746125.995, 3375475.211 1746115.874, 3375482.44 1746099.969, 3375491.477 1746079.004, 3375502.321 1746052.977, 3375510.629 1746031.691, 3375516.401 1746015.145, 3375519.655 1746007.554, 3375520.389 1746008.918, 3375522.564 1746006.709, 3375526.179 1746000.925, 3375533.408 1745985.743, 3375544.252 1745961.163, 3375557.627 1745924.654, 3375573.532 1745876.217, 3375586.545 1745844.769, 3375596.666 1745830.31, 3375604.98 1745811.513, 3375611.486 1745788.379, 3375612.932 1745770.666, 3375609.318 1745758.376, 3375602.088 1745749.339, 3375591.244 1745743.556, 3375582.93 1745733.073, 3375577.146 1745717.891, 3375564.856 1745701.625, 3375546.06 1745684.274, 3375518.588 1745670.538, 3375482.44 1745660.417, 3375447.739 1745644.512, 3375414.483 1745622.824, 3375378.336 1745602.943, 3375339.297 1745584.869, 3375303.872 1745566.434, 3375272.063 1745547.637, 3375245.675 1745533.901, 3375224.709 1745525.226, 3375208.443 1745519.442, 3375196.876 1745516.55, 3375179.887 1745501.73, 3375157.475 1745474.981, 3375135.425 1745455.461, 3375113.737 1745443.171, 3375095.663 1745437.026, 3375081.204 1745437.026, 3375069.637 1745441.002, 3375060.962 1745448.955, 3375059.154 1745459.799, 3375064.215 1745473.535, 3375084.819 1745487.994, 3375120.966 1745503.176, 3375148.8 1745519.442, 3375168.32 1745536.793, 3375183.501 1745550.529, 3375194.346 1745560.65, 3375205.913 1745569.687, 3375218.203 1745577.639, 3375228.324 1745588.845, 3375236.277 1745603.304, 3375249.651 1745613.064, 3375268.448 1745618.124, 3375282.907 1745632.945, 3375293.028 1745657.525, 3375304.957 1745670.538, 3375318.693 1745671.984, 3375332.067 1745667.285, 3375345.08 1745656.441, 3375357.37 1745650.657, 3375368.938 1745649.934, 3375377.974 1745653.187, 3375384.481 1745660.417, 3375403.639 1745682.105, 3375435.449 1745718.253, 3375454.607 1745738.495, 3375461.113 1745742.833, 3375474.126 1745754.039, 3375493.646 1745772.112, 3375494.007 1745797.777, 3375475.211 1745831.033, 3375464.367 1745858.143, 3375461.475 1745879.109, 3375459.306 1745903.327, 3375457.86 1745930.799, 3375455.751 1745962.551, 3375452.98 1745998.584, 3375448.28 1746022.079, 3375441.654 1746033.039))"
4,285343,BG,Сливен,Котел,2025-10-30 09:32:00+00:00,1,0.000000,0.0,0.000000,0.0,...,BG,0.860993,1.0,BG0000196,Reka Mochuritsa,2025-01-25,BG,B,NaN,"POLYGON ((5671266.06 2329759.043, 5671257.175 2329728.479, 5671247.224 2329717.107, 5671236.918 2329712.131, 5671226.256 2329713.553, 5671214.528 2329723.148, 5671201.734 2329740.918, 5671195.693 2329755.844, 5671196.403 2329767.927, 5671199.602 2329781.432, 5671205.288 2329796.359, 5671208.131 2329811.285, 5671208.131 2329826.211, 5671213.107 2329840.072, 5671223.058 2329852.866, 5671235.496 2329859.618, 5671250.423 2329860.329, 5671262.861 2329853.932, 5671272.812 2329840.427, 5671273.878 2329808.797, 5671266.06 2329759.043))"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12034,9158,PT,Tâmega e Sousa,Tendais,2015-04-03 22:00:00+00:00,79,6.097561,0.0,0.000000,0.0,...,PT,78.800950,79.0,PTCON0025,Serra de Montemuro,2024-12-13,PT,B,NaN,"POLYGON ((2811954.8 2173615.327, 2812186.311 2173483.035, 2812318.602 2173119.232, 2812417.821 2172755.429, 2812318.602 2172556.991, 2812020.945 2172523.918, 2811786.285 2172582.583, 2811568.829 2172779.653, 2811425.632 2173185.378, 2811557.924 2173549.181, 2811954.8 2173615.327))"
12035,319,PT,Área Metropolitana do Porto,Tropeço,2015-04-01 22:00:00+00:00,490,3.271984,0.0,15.337423,0.0,...,PT,489.801183,490.0,PTCON0047,Serras da Freita e Arada,2024-12-13,PT,B,NaN,"POLYGON ((2787922.638 2166023.737, 2787366.257 2165980.938, 2787147.209 2165980.938, 2787149.034 2165985.155, 2787152.055 2165995.085, 2787152.351 2166005.464, 2787149.59 2166014.311, 2787147.292 2166023, 2787145.418 2166034.633, 2787141.986 2166047.827, 2787142.537 2166062.236, 2787143.74 2166073.849, 2787146.662 2166085.074, 2787153.313 2166093.483, 2787160.132 2166100.806, 2787166.043 2166106.893, 2787175.643 2166113.267, 2787185.222 2166121.193, 2787191.134 2166127.28, 2787200.417 2166134.277, 2787208.164 2166141.089, 2787218.08 2166146.647, 2787225.195 2166154.703, 2787232.142 2166163.847, 2787236.792 2166172.229, 2787239.883 2166182.173, 2787243.901 2166191.8, 2787246.273 2166202.801, 2787247.737 2166212.567, 2787248.127 2166222.185, 2787247.886 2166233.047, 2787247.053 2166242.053, 2787246.811 2166252.915, 2787244.756 2166261.308, 2787243.104 2166274.195, 2787241.59 2166288.037, 2787243.213 2166297.206, 2787245.595 2166307.146, 2787247.702 2166314.607, 2787249.64 2166323.153, 2787252.694 2166328.747, 2787260.009 2166332.411, 2787269.601 2166338.388, 2787278.455 2166342.043, 2787286.864 2166344.305, 2787296.624 2166347.633, 2787309.037 2166349.559, 2787317.293 2166351.578, 2787326.644 2166352.195, 2787335.679 2166353.433, 2787344.566 2166354.208, 2787354.36 2166356.217, 2787363.08 2166358.078, 2787373.821 2166358.22, 2787383.171 2166358.836, 2787392.059 2166359.611, 2787402.316 2166361.462, 2787409.665 2166362.246, 2787417.523 2166359.588, 2787427.067 2166357.385, 2787434.145 2166355.507, 2787450.444 2166340.728, 2787461.287 2166329.889, 2787468.11 2166323.981, 2787476.199 2166314.505, 2787484.898 2166305.335, 2787493.115 2166297.873, 2787500.972 2166292.222, 2787512.974 2166287.259, 2787525.945 2166285.053, 2787534.177 2166284.361, 2787543.294 2166284.389, 2787553.381 2166287.461, 2787562.069 2166291.431, 2787572.882 2166296.787, 2787585.548 2166301.163, 2787593.661 2166304.833, 2787601.143 2166308.363, 2787610.25 2166313.027, 2787619.357 2166317.691, 2787628.844 2166322.225, 2787637.207 2166325.877, 2787645.571 2166329.528, 2787656.461 2166334.644, 2787663.602 2166337.241, 2787672.748 2166340.843, 2787679.905 2166342.169, 2787686.804 2166344.005, 2787695.861 2166344.684, 2787704.312 2166343.46, 2787713.281 2166341.445, 2787725.184 2166336.742, 2787734.687 2166332.436, 2787743.932 2166328.64, 2787751.188 2166322.568, 2787758.737 2166313.444, 2787765.646 2166304.96, 2787773.316 2166296.217, 2787779.151 2166288.664, 2787786.781 2166278.811, 2787794.361 2166268.052, 2787803.405 2166256.029, 2787810.881 2166248.338, 2787818.066 2166238.269, 2787825.18 2166229.082, 2787830.393 2166220.541, 2787837.474 2166208.821, 2787842.996 2166195.957, 2787846 2166184.216, 2787849.253 2166174.585, 2787851.157 2166162.039, 2787854.58 2166148.975, 2787857.211 2166138.712, 2787860.464 2166129.081, 2787867.361 2166120.317, 2787875.893 2166110.585, 2787883.202 2166107.597, 2787897.575 2166104.31, 2787910.397 2166102.355, 2787920.849 2166101.711, 2787927.188 2166100.71, 2787934.202 2166098.166, 2787946.677 2166096.554, 2787957.01 2166093.801, 2787963.592 2166091.994, 2787922.638 2166023.737))"
12036,155,PT,Alto Tâmega,Outeiro,2015-04-01 22:00:00+00:00,105,0.000000,0.0,0.000000,0.0,...,PT,104.726902,105.0,PTZPE0002,Serra do Gerês,2024-12-13,PT,A,NaN,"POLYGON ((2836948.578 2253570.677, 2836990.912 2253803.511, 2836948.578 2253972.845, 2836842.745 2254057.512, 2836588.744 2254142.179, 2836398.244 2254290.346, 2836439.429 2254558.049, 2836504.565 2254522.079, 2836556.537 2254493.502, 2836602.517 2254462.025, 2836649.603 2254426.802, 2836694.55 2254393.521, 2836741.377 2254359.842, 2836777.02 2254402.281, 2836831.564 2254409.044, 2836880 2254382.047, 2836952.733 2254339.666, 2836990.558 2254298.424, 2836988.586 2254241.249, 2837006.74 2254188.768, 2837062.691 2254176.843, 2837112.88 2254146.261, 2837133.711 2254094.278, 2837145.421 2254039.588, 2837150.939 2254018.394, 2837165.088 2254006.444, 2837161.822 2253970.422, 2837160.846 2253959.668, 2837164.34 2253951.915, 2837188.312 2253898.702, 2837152.367 2253847.525, 2837136.777 2253825.327, 2837140.376 2253821.874, 2837168.073 2253795.298, 2837141.828 2253763.51, 2837124.603 2253729.499, 2837135.123 2253691.838, 2837127.602 2253658.623, 2837102.041 2253629.855, 2837029.326 2253603.144, 2836991.932 2253558.674, 2836981.189 2253545.898, 2836968.036 2253531.761, 2836948.578 2253570.677))"
12037,155,PT,Alto Tâmega,Outeiro,2015-04-01 22:00:00+00:00,105,0.000000,0.0,0.000000,0.0,...,PT,104.726902,105.0,PTCON0001,Peneda / Gerês,2024-12-13,PT,B,NaN,"POLYGON ((2837414.246 2253316.677, 2837308.412 2253253.177, 2837160.245 2253253.177, 2837012.078 2253443.677, 2836948.578 2253570.677, 2836990.912 2253803.511, 2836948.578 2253972.845, 2836842.745 2254057.512, 2836588.744 2254142.179, 2836398.244 2254290.346, 2836440.577 2254565.513, 2836652.244 2254734.846, 2836969.745 2254756.013, 2837308.412 2254650.18, 2837477.746 2254459.679, 2837456.579 2254248.012, 2837498.913 2253909.345, 2837625.913 2253591.844, 2837520.079 2253401.344, 2837414.246 2253316.677))"

In [18]:
overlaps.columns.tolist()

['id',
 'country',
 'province',
 'commune',
 'firedate',
 'area_ha',
 'broadleaved_forest_pct',
 'coniferous_forest_pct',
 'mixed_forest_pct',
 'sclerophyllous_vegetation_pct',
 'transitional_woodland_shrub_pct',
 'other_natural_land_cover_pct',
 'agricultural_areas_pct',
 'artificial_surfaces_pct',
 'other_land_cover_pct',
 'natura2000_pct',
 'lastupdate',
 'year',
 'month',
 'broadleaved_forest_ha',
 'coniferous_forest_ha',
 'mixed_forest_ha',
 'sclerophyllous_vegetation_ha',
 'transitional_woodland_shrub_ha',
 'other_natural_land_cover_ha',
 'agricultural_areas_ha',
 'artificial_surfaces_ha',
 'other_land_cover_ha',
 'natura2000_ha',
 'forests_ha',
 'natural_vegetation_ha',
 'geometry_area_ha',
 'nuts3_id',
 'nuts3_name',
 'nuts3_urban_rural',
 'nuts3_mountain',
 'nuts3_coastal',
 'nuts2_name',
 'nuts1_name',
 'nuts_country',
 'total_geometry_area_ha',
 'geometry_area_ha_normalized',
 'SITECODE',
 'SITENAME',
 'RELEASE_DA',
 'MS',
 'SITETYPE',
 'INSPIRE_ID',
 'geometry']

In [19]:
overlaps["overlap_natura2k_ha"] = overlaps.geometry.area / 10_000

In [20]:
overlaps["official_link"] = (
    "https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site="
    + overlaps["SITECODE"]
)

In [21]:
overlaps_large = overlaps[
    overlaps["area_ha"] >= 5000
].copy()

In [22]:
repeated_sites = (
    overlaps_large
    .groupby(["SITECODE", "SITENAME"], dropna=False)
    .agg(
        fire_count=("id", "nunique"),
        fire_ids=("id", lambda x: sorted(x.dropna().unique())),
        years=("year", lambda x: sorted(x.dropna().unique())),
        months=("month", lambda x: sorted(x.dropna().unique())),
        years_affected=("year", "nunique"),
        countries=("country", lambda x: sorted(x.dropna().unique())),
        nuts3_names=("nuts3_name", lambda x: sorted(x.dropna().unique())),
        provinces=("province", lambda x: sorted(x.dropna().unique())),
        total_overlap_ha=("overlap_natura2k_ha", "sum")
    )
    .reset_index()
)

repeated_sites = (
    repeated_sites[repeated_sites["fire_count"] > 1]
    .sort_values(["years_affected", "total_overlap_ha"], ascending=False)
)

repeated_sites["official_link"] = (
    "https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site="
    + repeated_sites["SITECODE"]
)
repeated_sites.to_excel("repeated_sites_natura2k_decade_fire_season.xlsx", index=False)
repeated_sites

,SITECODE,SITENAME,fire_count,fire_ids,years,years_affected,countries,nuts3_names,provinces,total_overlap_ha,official_link
153,PTCON0014,Serra da Estrela,7,"[10293, 11573, 12587, 209050, 209560, 277927, 278350]","[2017, 2022, 2025]",3,[PT],"[Beiras e Serra da Estrela, Região de Coimbra]","[Beiras e Serra da Estrela, Região de Coimbra]",45523.804768,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=PTCON0014
178,PTZPE0038,Douro Internacional e Vale do Águeda,3,"[11551, 278497, 619]","[2016, 2017, 2025]",3,[PT],"[Douro, Terras de Trás-os-Montes]",[Douro],17415.761694,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=PTZPE0038
150,PTCON0003,Alvão / Marão,4,"[209459, 243297, 244947, 277291]","[2022, 2024, 2025]",3,[PT],"[Alto Tâmega e Barroso, Ave, Douro, Tâmega e Sousa]","[Alto Tâmega, Douro, Tâmega e Sousa]",15108.695453,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=PTCON0003
168,PTCON0059,Rio Paiva,4,"[244928, 276659, 278349, 888]","[2016, 2024, 2025]",3,[PT],"[Douro, Tâmega e Sousa, Viseu Dão Lafões, Área Metropolitana do Porto]","[Tâmega e Sousa, Viseu Dão Lafões, Área Metropolitana do Porto]",10181.681996,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=PTCON0059
155,PTCON0022,Douro Internacional,3,"[11551, 278497, 619]","[2016, 2017, 2025]",3,[PT],"[Douro, Terras de Trás-os-Montes]",[Douro],1343.264754,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=PTCON0022
31,ES1130002,Macizo Central,3,"[208294, 278475, 278504]","[2022, 2025]",2,[ES],[Ourense],[Ourense],30932.760752,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=ES1130002
160,PTCON0037,Monchique,2,"[14031, 218518]","[2018, 2023]",2,[PT],"[Alentejo Litoral, Algarve]","[Alentejo Litoral, Algarve]",26062.068426,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=PTCON0037
164,PTCON0047,Serras da Freita e Arada,2,"[244928, 888]","[2016, 2024]",2,[PT],"[Viseu Dão Lafões, Área Metropolitana do Porto]","[Viseu Dão Lafões, Área Metropolitana do Porto]",24314.017430,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=PTCON0047
30,ES1120001,Ancares - Courel,2,"[206702, 278475]","[2022, 2025]",2,[ES],"[León, Lugo, Ourense]","[Lugo, Ourense]",14697.551618,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=ES1120001
4,BG0002021,Sakar,2,"[233724, 275508]","[2024, 2025]",2,[BG],"[Хасково, Ямбол]","[Хасково, Ямбол]",14647.490618,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=BG0002021
0,BG0000212,Sakar,2,"[233724, 275508]","[2024, 2025]",2,[BG],[Хасково],"[Хасково, Ямбол]",11045.040442,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=BG0000212
91,ES6170010,Sierras Bermeja y Real,2,"[203085, 55350]","[2021, 2022]",2,[ES],[Málaga],[Málaga],11009.564353,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=ES6170010
158,PTCON0027,Carregal do Sal,2,"[10293, 243167]","[2017, 2024]",2,[PT],"[Beiras e Serra da Estrela, Região de Coimbra, Viseu Dão Lafões]","[Região de Coimbra, Viseu Dão Lafões]",9885.053365,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=PTCON0027
149,PTCON0001,Peneda / Gerês,2,"[17, 276834]","[2016, 2025]",2,[PT],"[Alto Minho, Cávado]",[Alto Minho],9796.314063,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=PTCON0001
174,PTZPE0002,Serra do Gerês,2,"[17, 276834]","[2016, 2025]",2,[PT],"[Alto Minho, Cávado]",[Alto Minho],8765.458216,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=PTZPE0002
69,ES4190110,Sierra de la Cabrera,2,"[10941, 278477]","[2017, 2025]",2,[ES],"[León, Ourense, Zamora]","[León, Ourense]",6733.728113,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=ES4190110
159,PTCON0028,Serra da Gardunha,2,"[11550, 277927]","[2017, 2025]",2,[PT],"[Beira Baixa, Beiras e Serra da Estrela]",[Beiras e Serra da Estrela],6248.464889,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=PTCON0028
21,ES0000355,Hurdes,2,"[205334, 216799]","[2022, 2023]",2,[ES],"[Cáceres, Salamanca]",[Cáceres],5461.907194,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=ES0000355
72,ES4320011,Las Hurdes,2,"[205334, 216799]","[2022, 2023]",2,[ES],"[Cáceres, Salamanca]",[Cáceres],5461.907194,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=ES4320011
129,GR3000001,OROS PARNITHA,2,"[219406, 51943]","[2021, 2023]",2,[EL],"[Ανατολική Αττική, Δυτική Αττική]","[Ανατολική Αττική, Δυτική Αττική]",5012.103426,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=GR3000001
49,ES4130024,Sierra de la Cabrera - ZEPA,2,"[10941, 278477]","[2017, 2025]",2,[ES],"[León, Ourense, Zamora]","[León, Ourense]",4915.159719,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=ES4130024
24,ES0000370,Sierra de Gata y Valle de las Pilas,2,"[216799, 9098]","[2015, 2023]",2,[ES],"[Cáceres, Salamanca]",[Cáceres],3350.703241,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=ES0000370
73,ES4320037,Sierra de Gata,2,"[216799, 9098]","[2015, 2023]",2,[ES],"[Cáceres, Salamanca]",[Cáceres],2509.321080,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=ES4320037
126,GR2530005,ORI GERANEIA,2,"[14384, 49326]","[2018, 2021]",2,[EL],"[Δυτική Αττική, Κορινθία]",[Δυτική Αττική],1802.657598,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=GR2530005
165,PTCON0051,Complexo do Açor,5,"[10165, 10293, 12302, 277927, 278350]","[2017, 2025]",2,[PT],"[Beiras e Serra da Estrela, Região de Coimbra]","[Beiras e Serra da Estrela, Região de Coimbra]",1787.650137,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=PTCON0051
92,ES6170016,Valle del Río del Genal,2,"[203085, 55350]","[2021, 2022]",2,[ES],[Málaga],[Málaga],1560.420026,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=ES6170016
2,BG0000218,Derventski vazvishenia 1,2,"[234291, 275508]","[2024, 2025]",2,[BG],"[Хасково, Ямбол]",[Ямбол],1478.848213,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=BG0000218
70,ES4190134,Lagunas de Tera y Vidriales,3,"[203513, 206474, 277940]","[2022, 2025]",2,[ES],[Zamora],[Zamora],1099.607844,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=ES4190134
5,BG0002026,Derventski vazvishenia,2,"[234291, 275508]","[2024, 2025]",2,[BG],[Ямбол],[Ямбол],839.568669,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=BG0002026
170,PTCON0061,Ria de Aveiro,2,"[11818, 8255]","[2016, 2017]",2,[PT],[Região de Aveiro],"[Região de Aveiro, Região de Coimbra]",631.291255,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=PTCON0061
35,ES1130009,Serra da Enciña da Lastra,2,"[206648, 278475]","[2022, 2025]",2,[ES],[Ourense],[Ourense],154.480739,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=ES1130009
65,ES4190033,Sierra de la Culebra,2,"[203513, 206474]",[2022],1,[ES],[Zamora],[Zamora],26992.988541,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=ES4190033
68,ES4190105,Lago de Sanabria y alrededores,2,"[278347, 278477]",[2025],1,[ES],"[León, Ourense, Zamora]",[Ourense],13580.526438,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=ES4190105
131,GR4130003,VOREIA CHIOS,2,"[272070, 278150]",[2025],1,[EL],[Χίος],[Χίος],6538.878114,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=GR4130003
48,ES4130022,Montes Aquilanos,2,"[277940, 277944]",[2025],1,[ES],[León],"[León, Zamora]",6437.824088,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=ES4130022
33,ES1130007,Pena Trevinca,2,"[278347, 278477]",[2025],1,[ES],"[León, Ourense, Zamora]",[Ourense],5313.149681,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=ES1130007
25,ES0000437,Pena Trevinca,2,"[278347, 278477]",[2025],1,[ES],"[León, Ourense, Zamora]",[Ourense],5184.720052,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=ES0000437
169,PTCON0060,Serra da Lousã,2,"[10170, 585]",[2017],1,[PT],"[Região de Coimbra, Região de Leiria]","[Região de Leiria, Viseu Dão Lafões]",1944.779955,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=PTCON0060
19,ES0000210,Alto Sil,2,"[277955, 279404]",[2025],1,[ES],[León],[León],365.373525,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=ES0000210
104,FR7200696,Domaine départemental d'Hostens,2,"[206257, 208962]",[2022],1,[FR],[Gironde],[Gironde],68.718660,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=FR7200696

In [23]:
pd.set_option("display.max_colwidth", None)
repeated_sites

,SITECODE,SITENAME,fire_count,fire_ids,years,years_affected,countries,nuts3_names,provinces,total_overlap_ha,official_link
153,PTCON0014,Serra da Estrela,7,"[10293, 11573, 12587, 209050, 209560, 277927, 278350]","[2017, 2022, 2025]",3,[PT],"[Beiras e Serra da Estrela, Região de Coimbra]","[Beiras e Serra da Estrela, Região de Coimbra]",45523.804768,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=PTCON0014
178,PTZPE0038,Douro Internacional e Vale do Águeda,3,"[11551, 278497, 619]","[2016, 2017, 2025]",3,[PT],"[Douro, Terras de Trás-os-Montes]",[Douro],17415.761694,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=PTZPE0038
150,PTCON0003,Alvão / Marão,4,"[209459, 243297, 244947, 277291]","[2022, 2024, 2025]",3,[PT],"[Alto Tâmega e Barroso, Ave, Douro, Tâmega e Sousa]","[Alto Tâmega, Douro, Tâmega e Sousa]",15108.695453,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=PTCON0003
168,PTCON0059,Rio Paiva,4,"[244928, 276659, 278349, 888]","[2016, 2024, 2025]",3,[PT],"[Douro, Tâmega e Sousa, Viseu Dão Lafões, Área Metropolitana do Porto]","[Tâmega e Sousa, Viseu Dão Lafões, Área Metropolitana do Porto]",10181.681996,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=PTCON0059
155,PTCON0022,Douro Internacional,3,"[11551, 278497, 619]","[2016, 2017, 2025]",3,[PT],"[Douro, Terras de Trás-os-Montes]",[Douro],1343.264754,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=PTCON0022
31,ES1130002,Macizo Central,3,"[208294, 278475, 278504]","[2022, 2025]",2,[ES],[Ourense],[Ourense],30932.760752,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=ES1130002
160,PTCON0037,Monchique,2,"[14031, 218518]","[2018, 2023]",2,[PT],"[Alentejo Litoral, Algarve]","[Alentejo Litoral, Algarve]",26062.068426,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=PTCON0037
164,PTCON0047,Serras da Freita e Arada,2,"[244928, 888]","[2016, 2024]",2,[PT],"[Viseu Dão Lafões, Área Metropolitana do Porto]","[Viseu Dão Lafões, Área Metropolitana do Porto]",24314.017430,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=PTCON0047
30,ES1120001,Ancares - Courel,2,"[206702, 278475]","[2022, 2025]",2,[ES],"[León, Lugo, Ourense]","[Lugo, Ourense]",14697.551618,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=ES1120001
4,BG0002021,Sakar,2,"[233724, 275508]","[2024, 2025]",2,[BG],"[Хасково, Ямбол]","[Хасково, Ямбол]",14647.490618,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=BG0002021
0,BG0000212,Sakar,2,"[233724, 275508]","[2024, 2025]",2,[BG],[Хасково],"[Хасково, Ямбол]",11045.040442,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=BG0000212
91,ES6170010,Sierras Bermeja y Real,2,"[203085, 55350]","[2021, 2022]",2,[ES],[Málaga],[Málaga],11009.564353,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=ES6170010
158,PTCON0027,Carregal do Sal,2,"[10293, 243167]","[2017, 2024]",2,[PT],"[Beiras e Serra da Estrela, Região de Coimbra, Viseu Dão Lafões]","[Região de Coimbra, Viseu Dão Lafões]",9885.053365,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=PTCON0027
149,PTCON0001,Peneda / Gerês,2,"[17, 276834]","[2016, 2025]",2,[PT],"[Alto Minho, Cávado]",[Alto Minho],9796.314063,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=PTCON0001
174,PTZPE0002,Serra do Gerês,2,"[17, 276834]","[2016, 2025]",2,[PT],"[Alto Minho, Cávado]",[Alto Minho],8765.458216,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=PTZPE0002
69,ES4190110,Sierra de la Cabrera,2,"[10941, 278477]","[2017, 2025]",2,[ES],"[León, Ourense, Zamora]","[León, Ourense]",6733.728113,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=ES4190110
159,PTCON0028,Serra da Gardunha,2,"[11550, 277927]","[2017, 2025]",2,[PT],"[Beira Baixa, Beiras e Serra da Estrela]",[Beiras e Serra da Estrela],6248.464889,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=PTCON0028
21,ES0000355,Hurdes,2,"[205334, 216799]","[2022, 2023]",2,[ES],"[Cáceres, Salamanca]",[Cáceres],5461.907194,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=ES0000355
72,ES4320011,Las Hurdes,2,"[205334, 216799]","[2022, 2023]",2,[ES],"[Cáceres, Salamanca]",[Cáceres],5461.907194,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=ES4320011
129,GR3000001,OROS PARNITHA,2,"[219406, 51943]","[2021, 2023]",2,[EL],"[Ανατολική Αττική, Δυτική Αττική]","[Ανατολική Αττική, Δυτική Αττική]",5012.103426,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=GR3000001
49,ES4130024,Sierra de la Cabrera - ZEPA,2,"[10941, 278477]","[2017, 2025]",2,[ES],"[León, Ourense, Zamora]","[León, Ourense]",4915.159719,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=ES4130024
24,ES0000370,Sierra de Gata y Valle de las Pilas,2,"[216799, 9098]","[2015, 2023]",2,[ES],"[Cáceres, Salamanca]",[Cáceres],3350.703241,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=ES0000370
73,ES4320037,Sierra de Gata,2,"[216799, 9098]","[2015, 2023]",2,[ES],"[Cáceres, Salamanca]",[Cáceres],2509.321080,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=ES4320037
126,GR2530005,ORI GERANEIA,2,"[14384, 49326]","[2018, 2021]",2,[EL],"[Δυτική Αττική, Κορινθία]",[Δυτική Αττική],1802.657598,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=GR2530005
165,PTCON0051,Complexo do Açor,5,"[10165, 10293, 12302, 277927, 278350]","[2017, 2025]",2,[PT],"[Beiras e Serra da Estrela, Região de Coimbra]","[Beiras e Serra da Estrela, Região de Coimbra]",1787.650137,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=PTCON0051
92,ES6170016,Valle del Río del Genal,2,"[203085, 55350]","[2021, 2022]",2,[ES],[Málaga],[Málaga],1560.420026,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=ES6170016
2,BG0000218,Derventski vazvishenia 1,2,"[234291, 275508]","[2024, 2025]",2,[BG],"[Хасково, Ямбол]",[Ямбол],1478.848213,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=BG0000218
70,ES4190134,Lagunas de Tera y Vidriales,3,"[203513, 206474, 277940]","[2022, 2025]",2,[ES],[Zamora],[Zamora],1099.607844,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=ES4190134
5,BG0002026,Derventski vazvishenia,2,"[234291, 275508]","[2024, 2025]",2,[BG],[Ямбол],[Ямбол],839.568669,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=BG0002026
170,PTCON0061,Ria de Aveiro,2,"[11818, 8255]","[2016, 2017]",2,[PT],[Região de Aveiro],"[Região de Aveiro, Região de Coimbra]",631.291255,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=PTCON0061
35,ES1130009,Serra da Enciña da Lastra,2,"[206648, 278475]","[2022, 2025]",2,[ES],[Ourense],[Ourense],154.480739,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=ES1130009
65,ES4190033,Sierra de la Culebra,2,"[203513, 206474]",[2022],1,[ES],[Zamora],[Zamora],26992.988541,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=ES4190033
68,ES4190105,Lago de Sanabria y alrededores,2,"[278347, 278477]",[2025],1,[ES],"[León, Ourense, Zamora]",[Ourense],13580.526438,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=ES4190105
131,GR4130003,VOREIA CHIOS,2,"[272070, 278150]",[2025],1,[EL],[Χίος],[Χίος],6538.878114,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=GR4130003
48,ES4130022,Montes Aquilanos,2,"[277940, 277944]",[2025],1,[ES],[León],"[León, Zamora]",6437.824088,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=ES4130022
33,ES1130007,Pena Trevinca,2,"[278347, 278477]",[2025],1,[ES],"[León, Ourense, Zamora]",[Ourense],5313.149681,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=ES1130007
25,ES0000437,Pena Trevinca,2,"[278347, 278477]",[2025],1,[ES],"[León, Ourense, Zamora]",[Ourense],5184.720052,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=ES0000437
169,PTCON0060,Serra da Lousã,2,"[10170, 585]",[2017],1,[PT],"[Região de Coimbra, Região de Leiria]","[Região de Leiria, Viseu Dão Lafões]",1944.779955,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=PTCON0060
19,ES0000210,Alto Sil,2,"[277955, 279404]",[2025],1,[ES],[León],[León],365.373525,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=ES0000210
104,FR7200696,Domaine départemental d'Hostens,2,"[206257, 208962]",[2022],1,[FR],[Gironde],[Gironde],68.718660,https://natura2000.eea.europa.eu/Natura2000/SDF.aspx?site=FR7200696

In [26]:
df_3035_all = df.to_crs(natura.crs)
overlaps_all = gpd.overlay(
    df_3035_all,
    natura,
    how="intersection",
    keep_geom_type=True
)
overlaps_all["overlap_natura2k_ha"] = overlaps.geometry.area / 10_000

In [28]:
overlaps_medium_large = overlaps_all[
    overlaps_all["area_ha"] >= 1000
].copy()

repeated_sites2 = (
    overlaps_medium_large
    .groupby(["SITECODE", "SITENAME"], dropna=False)
    .agg(
        fire_count=("id", "nunique"),
        fire_ids=("id", lambda x: sorted(x.dropna().unique())),
        years=("year", lambda x: sorted(x.dropna().unique())),
        months=("month", lambda x: sorted(x.dropna().unique())),
        years_affected=("year", "nunique"),
        countries=("country", lambda x: sorted(x.dropna().unique())),
        nuts3_names=("nuts3_name", lambda x: sorted(x.dropna().unique())),
        provinces=("province", lambda x: sorted(x.dropna().unique())),
        total_overlap_ha=("overlap_natura2k_ha", "sum")
    )
    .reset_index()
)

repeated_sites2 = (
    repeated_sites2[repeated_sites2["fire_count"] > 1]
    .sort_values(["years_affected", "total_overlap_ha"], ascending=False)
)

repeated_sites2 = repeated_sites2.round(2)
repeated_sites2.to_excel("repeated_sites_above1k_ha_ALL.xlsx", index=False)

repeated_sites2

,SITECODE,SITENAME,fire_count,fire_ids,years,months,years_affected,countries,nuts3_names,provinces,total_overlap_ha
474,ROSPA0031,Delta Dunării și Complexul Razim - Sinoie,79,"[10264, 11534, 11605, 12190, 12470, 12776, 12794, 12969, 15213, 15674, 15692, 15747, 15788, 15971, 16050, 16093, 16426, 17659, 17887, 180442, 181344, 183648, 183649, 183657, 183664, 190199, 19156, 192631, 19305, 19311, 19371, 19468, 19545, 19614, 19750, 198984, 19915, 200517, 200533, 211164, 211167, 211168, 211810, 211812, 211815, 213342, 213574, 216991, 22098, 22116, 22294, 234328, 23998, 24412, 256334, 258178, 258254, 258523, 258530, 265255, 265521, 265564, 265593, 267173, 267174, 268177, 268238, 268239, 270324, 281024, 43174, 45031, 45053, 46395, 46765, 47173, 47724, 59220, 9218]","[2015, 2016, 2017, 2019, 2020, 2021, 2022, 2023, 2024, 2025]","[April, August, February, January, July, March, November, October, September]",10,[RO],"[Constanţa, Tulcea]","[Constanţa, Tulcea]",3592.05
469,ROSCI0065,Delta Dunării,79,"[10264, 11534, 11605, 12190, 12470, 12776, 12794, 12969, 15213, 15674, 15692, 15747, 15788, 15971, 16050, 16093, 16426, 17659, 17887, 180442, 181344, 183648, 183649, 183657, 183664, 190199, 19156, 192631, 19305, 19311, 19371, 19468, 19545, 19614, 19750, 198984, 19915, 200517, 200533, 211164, 211167, 211168, 211810, 211812, 211815, 213342, 213574, 216991, 22098, 22116, 22294, 234328, 23998, 24412, 256334, 258178, 258254, 258523, 258530, 265255, 265521, 265564, 265593, 267173, 267174, 268177, 268238, 268239, 270324, 281024, 43174, 45031, 45053, 46395, 46765, 47173, 47724, 59220, 9218]","[2015, 2016, 2017, 2019, 2020, 2021, 2022, 2023, 2024, 2025]","[April, August, February, January, July, March, November, October, September]",10,[RO],"[Constanţa, Tulcea]","[Constanţa, Tulcea]",3203.33
426,PTCON0003,Alvão / Marão,9,"[13147, 205697, 209459, 243297, 244947, 245033, 277291, 277910, 50]","[2016, 2017, 2022, 2024, 2025]","[August, July, October, September]",5,[PT],"[Alto Tâmega e Barroso, Ave, Douro, Tâmega e Sousa]","[Alto Tâmega, Douro, Tâmega e Sousa]",1068.34
17,BG0002021,Sakar,10,"[218789, 219719, 232194, 233724, 275508, 281009, 370, 41712, 41713, 984]","[2016, 2020, 2023, 2024, 2025]","[August, July, June, September]",5,[BG],"[Хасково, Ямбол]","[Хасково, Ямбол]",892.46
1,BG0000212,Sakar,10,"[218789, 219719, 232194, 233724, 275508, 277499, 281009, 370, 41713, 984]","[2016, 2020, 2023, 2024, 2025]","[August, July, June, September]",5,[BG],[Хасково],"[Хасково, Ямбол]",58.49
...,...,...,...,...,...,...,...,...,...,...,...
388,ITA020027,"Monte Iato, Kumeta, Maganoce e Pizzo Parrino",2,"[51299, 51394]",[2021],[July],1,[IT],[Palermo],[Palermo],0.00
444,PTCON0045,Sicó / Alvaiázere,2,"[205499, 208327]",[2022],[July],1,[PT],"[Médio Tejo, Região de Leiria]","[Médio Tejo, Região de Leiria]",0.00
470,ROSCI0092,Igniș,2,"[24010, 24012]",[2020],[April],1,[RO],[Maramureş],[Maramureş],0.00
473,ROSPA0011,Blahnița,2,"[52307, 52308]",[2021],[August],1,[RO],[Mehedinţi],[Mehedinţi],0.00
476,ROSPA0134,Munții Gutâi,2,"[24010, 24012]",[2020],[April],1,[RO],[Maramureş],[Maramureş],0.00

In [25]:
repeated_sites_above1k_ha_greece = repeated_sites2[
    repeated_sites2['countries'].apply(lambda x: 'EL' in x if isinstance(x, list) else False)
]
repeated_sites_above1k_ha_greece.to_excel("repeated_sites_above1k_ha_greece_fire_season.xlsx", index=False)
repeated_sites_above1k_ha_greece

,SITECODE,SITENAME,fire_count,fire_ids,years,years_affected,countries,nuts3_names,provinces,total_overlap_ha
254,GR1110002,DASOS DADIAS - SOUFLI,2,"[206611, 218736]","[2022, 2023]",2,[EL],[Έβρος],[Έβρος],34393.86
256,GR1110005,VOUNA EVROU- POTAMOS LYRAS- SPILAIA DIDYMOTEICHOU KAI KEFALOVOUNOU,2,"[206611, 218736]","[2022, 2023]",2,[EL],[Έβρος],[Έβρος],34393.86
293,GR4130003,VOREIA CHIOS,3,"[232443, 272070, 278150]","[2024, 2025]",2,[EL],[Χίος],[Χίος],6539.38
286,GR3000001,OROS PARNITHA,2,"[219406, 51943]","[2021, 2023]",2,[EL],"[Ανατολική Αττική, Δυτική Αττική]","[Ανατολική Αττική, Δυτική Αττική]",5012.10
283,GR2540008,NOTIA MANI,2,"[13117, 42303]","[2017, 2020]",2,[EL],"[Λακωνία, Μεσσηνία]","[Λακωνία, Μεσσηνία]",3352.73
280,GR2530005,ORI GERANEIA,2,"[14384, 49326]","[2018, 2021]",2,[EL],"[Δυτική Αττική, Κορινθία]",[Δυτική Αττική],1802.66
274,GR2420010,OROS KANTILI,2,"[213578, 899]","[2016, 2021]",2,[EL],[Εύβοια],[Εύβοια],1093.46
276,GR2450004,PARALIAKI ZONI APO NAFPAKTO EOS ITEA - PERIOCHI PIGON CHILIADOU,2,"[204611, 52255]","[2021, 2022]",2,[EL],[Φωκίδα],[Φωκίδα],544.07
270,GR2210001,DYTIKES KAI VOREIOANATOLIKES AKTES ZAKYNTHOU,2,"[11698, 278130]","[2017, 2025]",2,[EL],[Ζάκυνθος],[Ζάκυνθος],331.45
294,GR4210005,"RODOS: AKRAMYTIS, ARMENISTIS, ATTAVYROS, REMATA KAI THALASSIA ZONI (KARAVOLA-ORMOS GLYFADA)",2,"[1026, 217438]","[2016, 2023]",2,[EL],"[Κάλυμνος, Κάρπαθος – Ηρωική Νήσος Κάσος, Κως, Ρόδος]","[Κάλυμνος, Κάρπαθος – Ηρωική Νήσος Κάσος, Κως, Ρόδος]",313.98
266,GR1150012,"THASOS (OROS YPSARIO KAI PARAKTIA ZONI) KAI NISIDES KOINYRA, XIRONISI",3,"[1162, 658, 8102]",[2016],1,[EL],"[Θάσος, Καβάλα]","[Θάσος, Καβάλα]",1746.21
282,GR2530007,KORINTHIAKOS KOLPOS,2,"[218846, 219396]",[2023],1,[EL],[Βοιωτία],[Βοιωτία],2.59

In [32]:
natura_ro = natura[natura['MS'] == 'RO']
natura_ro.to_file(
    "natura_ro.gpkg",
    driver="GPKG"
)